DISEASES = [
    {
        "name": "Bacterial Leaf Blight",
        "description": "Bacterial blight is caused by Xanthomonas oryzae pv. oryzae. It causes wilting of seedlings and yellowing and drying of leaves. The disease is most likely to develop in areas that have weeds and stubbles of infected plants. It can occur in both tropical and temperate environments, particularly in irrigated and rainfed lowland areas. In general, the disease favors temperatures at 25−34°C, with relative humidity above 70%. It is commonly observed when strong winds and continuous heavy rains occur, allowing the disease-causing bacteria to easily spread through ooze droplets on lesions of infected plants. Bacterial blight can be severe in susceptible rice varieties under high nitrogen fertilization.",
        "control_methods": [
            "Apply judicious level of fertilization (60-80 kg N/ha with required level of potassium) without sacrificing the yield.",
            "Neem oil 60 EC 3% (or) NSKE 5% is recommended for the control of bacterial blight.",
        ]
    },
    {
        "name": "Bacterial Leaf Streak",
        "description": "Bacterial leaf streak is caused by Xanthomonas oryzae pv. oryzicola. Infected plants show browning and drying of leaves. Under severe conditions, this could lead to reduced grain weight due to loss of photosynthetic area. Bacterial leaf streak occurs in areas with high temperature and high humidity. It is transmitted through seeds and infected stubbles to the next planting season. It can occur in fields where X. oryzae pv. oryzicola bacteria is present on leaves, in the water, or in the debris left after harvest. It can affect the plant during early stages, from maximum tillering to panicle initiation. Mature rice plants can easily recover from leaf streak and have minimal grain yield losses.",
        "control_methods": ["Spray fresh cowdung water extract 20%.", "Copper hydroxide 77 WP@1.25 kg/ha is also recommended."]
    },
    {
        "name": "Brown Spot",
        "description": "Brown spot has been historically largely ignored as one of the most common and most damaging rice diseases. Brown spot is a fungal disease that infects the coleoptile, leaves, leaf sheath, panicle branches, glumes, and spikelets. Its most observable damage is the numerous big spots on the leaves which can kill the whole leaf. When infection occurs in the seed, unfilled grains or spotted or discolored seeds are formed. The disease can develop in areas with high relative humidity (86−100%) and temperature between 16 and 36°C. It is common in unflooded and nutrient-deficient soil, or in soils that accumulate toxic substances. For infection to occur, the leaves must be wet for 8−24 hours. The fungus can survive in the seed for more than four years and can spread from plant to plant through air. Major sources of brown spot in the field include: infected seed, which give rise to infected seedlings, volunteer rice, infected rice debris, weeds. Brown spot can occur at all crop stages, but the infection is most critical during maximum tillering up to the ripening stages of the crop.",
        "control_methods": ["In endemic area, adopt seed treatment with Carbendazim (12%) + Mancozeb (63%)combination 75 WP @ 2 g/kg or Carbendazim 50 WP @ 2 g/kg or Mancozeb (63%) 75 WP @ 2g/litre or Mancozeb 75 WP @ 2.5 g/litre.", "Spray the following Metominostrobin @ 500ml/ha."]
    },
    {
        "name": "Rice Grassy Stunt Virus",
        "description": "Rice grassy stunt virus reduces yields by inhibiting panicle production. Rice grassy stunt virus affects rice crops in areas where continuous and year-round rice growing is practiced. The virus is transmitted between plants by insect vectors. Nymph and adult stage plant hoppers are common vectors for rice grassy stunt virus. The plant hoppers need to feed on an infected plant for at least 30 minutes to pick-up the virus. Plants can be infected at all growth stages. They are most vulnerable to infection at the tillering stage. Rice grassy stunt virus symptoms develop 10−12 days after infection. Infected stubble and volunteer rice are sources of rice grassy stunt virus. It cannot be transmitted via brown planthopper eggs.",
        "control_methods": ["Phosphamidon 40 SL 1000 ml/ha (or) Phosalone 35 EC 1500 ml/ha (or) Carbaryl 10 D 25 kg/ha (or) (or) Acephate 75 SP 625 gm/ha (or) Chlorpyriphos 20 EC 1250 ml/ha.", "Avoid close planting and provide 30 cm rogue spacing at every 2.5 to 3.0 m to reduce the pest incidence.", "plouging and harrowing the field to destroy stubbles right after harvest in order to eradicate other hosts."]
    },
    {
        "name": "Narrow Brown Spot",
        "description": "Narrow brown spot (also called narrow brown leaf spot, or rice Cercospora leaf spot) is caused by the fungus Sphaerulina oryzina (syn. Cercospora janseana, Cercospora oryzae) and can infect leaves, sheaths, and panicles. It leads to premature death of leaves and leaf sheaths, premature ripening of grains, and in severe cases, lodging of plants.  The disease usually occurs in potassium deficient soils, and in areas with temperature ranging from 25−28°C. It appears during the late growth stages of the rice crop, starting at heading stage. Plants are most susceptible during panicle initiation onwards, and damage becomes more severe as plants approach maturity. ",
        "control_methods": ["Spray the following: Metominostrobin @ 500ml/ha."]
    },
    {
        "name": "Rice Ragged Stunt Virus",
        "description": "Rice ragged stunt virus reduces yield by causing partially exerted panicles, unfilled grains and plant density loss. It is vector-transmitted from one plant to another by brown plant hoppers. Leaves of infected plants have a ragged appearance. Rice ragged stunt virus infection is particularly high in tropical conditions where rice is planted all-year-around and provides a continuous host for the brown plant hopper vector. The early instar nymphs of brown plant hoppers are more efficient transmitters of rice ragged stunt virus than brown plant hoppers at older stages. Brown plant hoppers contract the virus within 24 hours of feeding on an infected plant. They can transmit the virus to other plants after 6 hours of being infected with it and will remain infective for life. The virus is not transmitted via the brown plant hopper eggs. Infected stubble and volunteer rice are sources of rice grassy stunt virus. If plants are infected at seedling stage, they develop new leaves with symptoms two weeks after inoculation. Leaves developed after this and until heading will show only mild or no symptoms. From heading onwards infected plants show symptoms again on the upper leaves and flag leaves. Rice ragged stunt virus can affect up to 75% of plants in a crop. Depending on the extent of the damage infected plants will either produce partially exerted panicles and unfilled grains or produce few or no grains. Infected crops will suffer significant yield losses of up to 80%.",
        "control_methods": ["Preventive measures are more efficient against rice ragged stunt virus than direct-control measures. Once infected by the virus, a rice plant cannot be cured.", "Plant varieties resistant to brown planthopper.", "Using resistant varieties for ragged stunt management is probably the most important control measure. Contact your local agriculture office for up-to-date lists of varieties available.", "Practice synchronized planting.", "Plow infected stubbles under the field after harvest to reduce the virus source."]
    },
    {
        "name": "Rice Blast",
        "description": "Blast is caused by the fungus Magnaporthe oryzae. It can affect all above ground parts of a rice plant: leaf, collar, node, neck, parts of panicle, and sometimes leaf sheath. Blast can occur wherever blast spores are present. It occurs in areas with low soil moisture, frequent and prolonged periods of rain shower, and cool temperature in the daytime. In upland rice, large day-night temperature differences that cause dew formation on leaves and overall cooler temperatures favor the development of the disease. Rice can have blast in all growth stages. However, leaf blast incidence tends to lessen as plants mature and develop adult plant resistance to the disease. Rice blast is one of the most destructive diseases of rice. A leaf blast infection can kill seedlings or plants up to the tillering stage. At later growth stages, a severe leaf blast infection reduces leaf area for grain fill, reducing grain yield. Leaf blast can kill rice plants at seedling stage and cause yield losses in cases of severe infection.",
        "control_methods": ["In endemic areas, adopt seed treatment with Tricyclazole 75WP @ 2 g/kg or Carbendazim 50WP @ 1 g/kg. ", "Spray Tricyclazole 75 @ 0.6g/litre or Carpropamid 30 SC @1ml/litre. or Isoprothiolane 40 EC @ 1.5ml/litre or Iprobenphos 48 EC @2ml/litre or Propiconazole 25 EC@ 1ml/litre or Kasugamycin-B 3SL@2.5 ml/litre or Carbendazim 50 WP @ 1 g/litre.", "Metominostrobin 20 SC @ 500ml/ha (or) Azoxystrobin 25 SC @ 500 ml/ha."]
    },
    {
        "name": "False Smut",
        "description": "False smut causes chalkiness of grains which leads to reduction in grain weight. It also reduces seed germination.The disease can occur in areas with high relative humidity (>90%) and temperature ranging from 25−35 ºC. Rain, high humidity, and soils with high nitrogen content also favors disease development. Wind can spread the fungal spores from plant to plant. False smut is visible only after panicle exsertion. It can infect the plant during flowering stage. The disease affects the early flowering stage of the rice crop when the ovary is destroyed. The second stage of infection occurs when the spikelet nearly reaches maturity. These causes chalkiness and can reduce 1,000-grain weight. It also causes a reduction in seed germination of up to 35%. In damp weather, the disease can be severe and losses can reach 25%. In India, a yield loss of 7−75% was observed.",
        "control_methods": ["Spray Propiconazole 25 EC @ 1ml/litre or Chlorothalonil 75 WP@ 2 ml/litre or Copperoxychloride at around flowering.", "Copper hydroxide 77 WP @ 1.25 kg/ha at boot leaf and 50% flowering stages."]
    },
    {
        "name": "Sheath Blight",
        "description": "Sheath blight is a fungal disease caused by Rhizoctonia solani. Infected leaves senesce or dry out and die more rapidly, young tillers can also be destroyed. As a result, the leaf area of the canopy can significantly be reduced by the disease. This reduction in leaf area, along with the diseased-induced senescence of leaves and young infected tillers are the primary causes of yield reduction. Sheath blight occurs in areas with high temperature (28−32°C),  high levels of nitrogen fertilizer, and relative humidity of crop canopy from 85−100%. Plants are more vulnerable to sheath blight during the rainy season. High seeding rate or close plant spacing, dense canopy, disease in the soil, sclerotia or infection bodies floating on the water, and growing of high yielding improved varieties also favor disease development. Sheath blight is considered to be an important disease next to rice blast. Rice sheath blight is an increasing concern for rice production especially in intensified production systems.",
        "control_methods": ["Spray Validamycin 3 L @ 2.5ml/litre or Thifluzamide 24 SC @ 0.75 g/litre or Hexaconazole 5 EC @ 2 ml/litre or Propiconazole 25 EC @ 1ml/litre or Carbendazim 50 WP @ 1g/litre.", "Azoxystrobin @ 500ml/ha."]
    },
    {
        "name": "Sheath Rot",
        "description": "Sheath rot is caused by Sarocladium oryzae. The disease reduces grain yield by retarding or aborting panicle emergence, and producing unfilled seeds and sterile panicles. Sheath rot also reduces grain quality by causing panicles to rot and grains to become discolored.Sheath rot is present in most of the rice growing countries worldwide, particularly in rainfed rice ecosystems and is more prevalent during wet than dry seasons. Its incidence increases with increasing planting density and in plants that provide entry points for the fungus, in the form of injuries and wounds caused by insects such as stem borers at panicle initiation stage. The fungus tends to cause rotting of the uppermost leaf sheaths enclosing young panicles, which retards or aborts their emergence. It can also occur in areas with high amounts of nitrogen fertilizer application and high relative humidity and temperatures (20−28°C) at heading to mature crop stages. Sheath rot infects the rice plant at all growth stages, but it is most destructive when infection occurs during or after the booting stage, before the emergence of the panicle.",
        "control_methods": ["In endemic area adopt seed treatment with Mancozeb 75 WP @ 2.5 g/kg or Captan 50 WP.", "Spray Mancozeb 75 WP @ 2.5g/kg or Propiconazole 25 EC @ 1 ml/litre or Hexaconazole 5 EC @ 2 ml/litre or Thiophanatemethyl 70 WP @ 1 g/litre."]
    },
    {
        "name": "Stem Rot",
        "description": "Stem rot leads to formation of lesions and production of chalky grains and unfilled panicles. The infection bodies or sclerotia are found in the upper soil layer. They survive in air-dry soil, buried moist rice soil, and in tap water. They can also survive on straw, which is buried in the soil. The sclerotia float on irrigation water and infect newly planted rice during land preparation. Infection is high on plants with wounds as a result of lodging or insect attack. The panicle moisture content and nitrogen fertilizer also influence disease development. The infection is seen on the rice crop during early heading and grain filling. The leaf sheaths decay and cause lodging and lower grain filling. It can cause heavy losses in many countries.",
        "control_methods": ["Addition of organic manure reduces the disease.", "Spray Iprobenphos 48 EC @ 2g/litre of Carbendazim 50 WP @ 1 g/litre or Thiophanate methyl 70 WP 1 g/litre or Isoprothiolane 40 EC @ 1.5 ml/litre."]
    },
    {
        "name": "Tungro Virus",
        "description": "Rice tungro disease is caused by the combination of two viruses, which are transmitted by leafhoppers. It causes leaf discoloration, stunted growth, reduced tiller numbers and sterile or partly filled grains. Tungro infects cultivated rice, some wild rice relatives and other grassy weeds commonly found in rice paddies. Tungro disease viruses are transmitted from one plant to another by leafhoppers that feed on tungro-infected plants. The most efficient vector is the green leafhopper. Leafhoppers can acquire the viruses from any part of the infected plant by feeding on it, even for a short time. It can, then, immediately transmit the viruses to other plants within 5−7 days. The viruses do not remain in the leafhopper's body unless it feeds again on an infected plant and re-acquires the viruses. Tungro infection can occur during all growth stages of the rice plant. It is most frequently seen during the vegetative phase. Plants are most vulnerable at tillering stage. Tungro incidence depends on the availability of the virus sources and vector population. Other than infected rice plants in the farmer's field, other primary sources for tungro, include: stubble of previous crops,new growth from infected stubbles that had not been properly plowed under and harrowed effectively,volunteer rice, infected plants in nearby rice fields. Seedlings raised in nurseries or seedbeds can also be infected with Tungro prior to transplanting and can be a primary source of virus. Transplanting seedlings from nurseries in tungro-infected areas has also shown to increase infection rates in the field, particularly, in cases where seedbed is in a tungro-endemic area or when the nursery duration is 5−6 weeks. However, this is not believed to be a very strong mechanism in initiating epidemics, because the competitiveness of tungro-infected seedlings is low; they can die rapidly after transplanting.",
        "control_methods": ["Remove and destroy infected plants and apply additional nitrogen for early recovery.", "Incorporate Phorate 10 G @ 12-15 kg/ha or Fipronil 0.4 G @ 25 kg/ha or nursery in top 2-5 cm layer of the soil before sowing of sprouted seeds. If such incorporation is not possible, broadcast the recommended insecticides 4-5 days after showing in a thin film of water and allow this water to seep completely.", "In the main crop, spray Carbaryl 50 WP @ 0.65 litre/ha or Fipronil 5 EC @ 1 litre/ha."]
    }

]
